package MetaAnn;

import java.awt.Toolkit;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiago Missão
 */
public class JFrameOpcao extends javax.swing.JFrame {

    /**
     * Creates new form Opção
     */
    private static JFrameCategoria JFRAME_CATEGORIA ;
    private static Opcao opcao_editada;
    private static boolean EDICAO;
    private Locale locale;
    
    public JFrameOpcao(Locale locale) {
        initComponents();
        setIcon();
        Text_Titulo_Anotacao.setDocument(new ValidaEntrada());
        Text_Titulo_Usuario.setDocument(new ValidaEntradaComCaracteres(15));
        EDICAO = false;
        this.locale = locale;
        internacionaliza();
    }

    public JFrameOpcao(JFrameCategoria JFrame_Categoria,Locale locale) {
        this(locale);
        this.JFRAME_CATEGORIA = JFrame_Categoria;
    }
    
    public JFrameOpcao(JFrameCategoria JFrame_Categoria,Opcao editada,Locale locale ){
        this(JFrame_Categoria,locale);
        this.opcao_editada = editada;
        Text_Titulo_Usuario.setText(editada.getValorUsuario());
        Text_Titulo_Anotacao.setText(editada.getValorAnotacao());
        EDICAO = true;
        
        internacionaliza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Titulo_Usuario = new javax.swing.JLabel();
        Text_Titulo_Usuario = new javax.swing.JTextField();
        Text_Titulo_Anotacao = new javax.swing.JTextField();
        Label_Titulo_Anotacao = new javax.swing.JLabel();
        Botao_Salvar = new javax.swing.JButton();
        Botao_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MetaAnn - Opção");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Label_Titulo_Usuario.setText("Título da Opção no COMBO");

        Label_Titulo_Anotacao.setText("Título da Opção no COMBO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Text_Titulo_Usuario)
                    .addComponent(Text_Titulo_Anotacao)
                    .addComponent(Label_Titulo_Anotacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(Label_Titulo_Usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Titulo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_Titulo_Anotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text_Titulo_Anotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Botao_Salvar.setText("Salvar");
        Botao_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SalvarActionPerformed(evt);
            }
        });

        Botao_Cancelar.setText("Cancelar");
        Botao_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(236, Short.MAX_VALUE)
                        .addComponent(Botao_Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_Cancelar)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_Cancelar)
                    .addComponent(Botao_Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void internacionaliza(){
    
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameOpcao.JFrameOpcao", locale);
        
        if(!EDICAO)
            setTitle("MetaAnn - " + bundle.getString("adicionarOpcao"));
        else
            setTitle("MetaAnn - " + bundle.getString("editarOpcao"));
        
        Botao_Cancelar.setText(bundle.getString("cancelar"));
        Botao_Salvar.setText(bundle.getString("salvar"));
        Label_Titulo_Usuario.setText(bundle.getString("mensagem1"));
        Label_Titulo_Anotacao.setText(bundle.getString("mensagem2"));
        
    }
    
    private void Botao_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_CancelarActionPerformed
        JFRAME_CATEGORIA.setEnabled(true);
        this.dispose();
        JFRAME_CATEGORIA.controlarBotoes();
    }//GEN-LAST:event_Botao_CancelarActionPerformed

    private void Botao_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SalvarActionPerformed
        /*
         *  Salva as configurações da Opcao
         *      Caso seja uma Edição atualiza o Elemento na Lista
         *      Caso contrario apenas adiciona este na Lista
         */
        
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameOpcao.JFrameOpcao", locale);
        
        String valorUsuario = Text_Titulo_Usuario.getText().toUpperCase();
        String valorAnotacao = Text_Titulo_Anotacao.getText().toUpperCase();
        
        if(valorUsuario.trim().length()==0){
            JOptionPane.showMessageDialog(this, bundle.getString("erroNomeOpcao"), bundle.getString("erroCampoObrig"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(valorAnotacao.trim().length()==0){
            JOptionPane.showMessageDialog(this, bundle.getString("erroValorOpcao"), bundle.getString("erroCampoObrig"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean completo;
        Opcao temp = new Opcao();
        
            temp.setValorUsuario(valorUsuario);
            temp.setValorAnotacao(valorAnotacao);
        
        if(EDICAO){
            completo = JFRAME_CATEGORIA.EditaOpcao(temp, opcao_editada);
        }
        
        else{
            completo = JFRAME_CATEGORIA.AdicionaOpcao(temp);
        }
        
        if(completo){
            JFRAME_CATEGORIA.setEnabled(true);
            this.dispose();
        }
        
        JFRAME_CATEGORIA.controlarBotoes();
    }//GEN-LAST:event_Botao_SalvarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JFRAME_CATEGORIA.setEnabled(true);
        JFRAME_CATEGORIA.controlarBotoes();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new JFrameOpcao().setVisible(true);
            }
        });
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Cancelar;
    private javax.swing.JButton Botao_Salvar;
    private javax.swing.JLabel Label_Titulo_Anotacao;
    private javax.swing.JLabel Label_Titulo_Usuario;
    private javax.swing.JTextField Text_Titulo_Anotacao;
    private javax.swing.JTextField Text_Titulo_Usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
