package MetaAnn;

import java.awt.Event;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiago Missão
 */
public class JFrameCategoria extends javax.swing.JFrame {

    /**
     * Creates new form Categoria
     */
    private MetaAnn META_ANN; // Instancia do METAANN
    private DefaultListModel OPCOES_MODEL = new DefaultListModel(); // LISTA DE ELEMENTOS DO JLIST
    private DefaultListModel CATEGORIAS_EXISTENTES = new DefaultListModel(); // Lista de Categorias Existentes
    private DefaultListModel DEPENDECIAS_DA_CATEGORIA = new DefaultListModel(); // Lista das Dependências da Categoria;
    private ArrayList<Opcao> OPCOES = new ArrayList<Opcao>();
    private Categoria CATEGORIA_EDITADA;
    private boolean TEXTOLIVRE = false;
    private boolean EDICAO = false;
    private Locale locale;
    
    public JFrameCategoria(Locale locale) {
        initComponents();
        setIcon();
        Text_Identificador_da_Categoria.setDocument(new ValidaEntrada());
        Text_Nome_Categoria.setDocument(new ValidaCaracteres(30));
        Lista_de_Opcoes.setModel(OPCOES_MODEL);
        Lista_de_Categorias.setModel(CATEGORIAS_EXISTENTES);
        Lista_de_Dependencias.setModel(DEPENDECIAS_DA_CATEGORIA);
        this.locale = locale;
        
        //Atalho de teclado para o botão de salvar
        KeyStroke keySave = KeyStroke.getKeyStroke(KeyEvent.VK_S, Event.CTRL_MASK); 
        Action performSave = new AbstractAction("Save") {  
            public void actionPerformed(ActionEvent e) {  
                 ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);
                 //Salvamento
                 if(!e.getActionCommand().equals(bundle.getString("salvar")))
                    Acao_Salvar();
            }
        }; 
        Botao_Salvar.setAction(performSave);
        Botao_Salvar.getActionMap().put("performSave", performSave);
        Botao_Salvar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keySave, "performSave");
        
        //Traduzir campos
        internacionaliza();
    }

    JFrameCategoria(MetaAnn Meta_Ann, Locale locale ) {
        this(locale);
        this.META_ANN = Meta_Ann;
        carregaListaDeCategorias();
        controlarBotoes();
    }
    
    JFrameCategoria(MetaAnn Meta_Ann,Categoria categoria,Locale locale){
        this(Meta_Ann,locale);
        EDICAO = true;
	this.CATEGORIA_EDITADA = categoria;
        internacionaliza();
        carregaEstado(categoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelNomeCategoria = new javax.swing.JLabel();
        Text_Nome_Categoria = new javax.swing.JTextField();
        jLabelOpcoes = new javax.swing.JLabel();
        Botao_Adiciona_Opcao = new javax.swing.JButton();
        Botao_Remove_Opcao = new javax.swing.JButton();
        Botao_Edita_Opcao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_de_Opcoes = new javax.swing.JList();
        Combo_Tipo_da_Categoria = new javax.swing.JComboBox();
        jLabelTipoCategoria = new javax.swing.JLabel();
        Text_Identificador_da_Categoria = new javax.swing.JTextField();
        Text_Texto_da_Categoria = new javax.swing.JTextField();
        jLabelIdentificadorCategoria = new javax.swing.JLabel();
        jLabelTextoCategoria = new javax.swing.JLabel();
        Botao_Opcao_Abaixo = new javax.swing.JButton();
        Botao_Opcao_Acima = new javax.swing.JButton();
        Text_Valor_Opcao = new javax.swing.JTextField();
        jLabel_Valor_Categoria = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelAdvanced = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_de_Categorias = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        Lista_de_Dependencias = new javax.swing.JList();
        Button_PassarTodos = new javax.swing.JButton();
        Button_PassarUm = new javax.swing.JButton();
        Botao_Corpus_Acima = new javax.swing.JButton();
        Button_VoltarUm = new javax.swing.JButton();
        Button_VoltarTodos = new javax.swing.JButton();
        Botao_Salvar = new javax.swing.JButton();
        Botao_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MetaAnn - Categoria");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelNomeCategoria.setText("Nome da Categoria");

        jLabelOpcoes.setText("Opções");

        Botao_Adiciona_Opcao.setMnemonic('A');
        Botao_Adiciona_Opcao.setText("Adicionar");
        Botao_Adiciona_Opcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Adiciona_OpcaoActionPerformed(evt);
            }
        });

        Botao_Remove_Opcao.setMnemonic('R');
        Botao_Remove_Opcao.setText("Remover");
        Botao_Remove_Opcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Remove_OpcaoActionPerformed(evt);
            }
        });

        Botao_Edita_Opcao.setMnemonic('E');
        Botao_Edita_Opcao.setText("Editar");
        Botao_Edita_Opcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Edita_OpcaoActionPerformed(evt);
            }
        });

        Lista_de_Opcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_de_OpcoesMouseClicked(evt);
            }
        });
        Lista_de_Opcoes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lista_de_OpcoesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(Lista_de_Opcoes);

        Combo_Tipo_da_Categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Opções Mutuamente Exclusivas", "Lista Simples de Opções", "Campo Textual" }));
        Combo_Tipo_da_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Tipo_da_CategoriaActionPerformed(evt);
            }
        });

        jLabelTipoCategoria.setText("Tipo da Categoria");

        Text_Identificador_da_Categoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_Identificador_da_CategoriaFocusLost(evt);
            }
        });
        Text_Identificador_da_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Identificador_da_CategoriaActionPerformed(evt);
            }
        });

        Text_Texto_da_Categoria.setEnabled(false);

        jLabelIdentificadorCategoria.setText("Identificador da Categoria");

        jLabelTextoCategoria.setText("Texto da Categoria");

        Botao_Opcao_Abaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MetaAnn/seta_baixo.png"))); // NOI18N
        Botao_Opcao_Abaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Opcao_AbaixoActionPerformed(evt);
            }
        });

        Botao_Opcao_Acima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MetaAnn/seta_cima.png"))); // NOI18N
        Botao_Opcao_Acima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Opcao_AcimaActionPerformed(evt);
            }
        });

        Text_Valor_Opcao.setEditable(false);
        Text_Valor_Opcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Valor_OpcaoActionPerformed(evt);
            }
        });

        jLabel_Valor_Categoria.setText("Valor da Opcao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabelTipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabelIdentificadorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Valor_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Valor_Opcao, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botao_Opcao_Acima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Botao_Opcao_Abaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botao_Adiciona_Opcao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Botao_Edita_Opcao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Botao_Remove_Opcao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_Texto_da_Categoria)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTextoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(Text_Identificador_da_Categoria)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Text_Nome_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Combo_Tipo_da_Categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoCategoria))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Nome_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Tipo_da_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdentificadorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Botao_Opcao_Acima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Botao_Opcao_Abaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Botao_Adiciona_Opcao)
                            .addComponent(Text_Identificador_da_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Botao_Edita_Opcao)
                            .addComponent(jLabelTextoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Botao_Remove_Opcao)
                            .addComponent(Text_Texto_da_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel_Valor_Categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Valor_Opcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jLabelAdvanced.setText(" Passe para a lista da direita as categorias das quais você desseja que esta categoria dependa.");

        Lista_de_Categorias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista_de_Categorias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lista_de_CategoriasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Lista_de_Categorias);

        Lista_de_Dependencias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista_de_Dependencias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Lista_de_DependenciasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(Lista_de_Dependencias);

        Button_PassarTodos.setText(">>");
        Button_PassarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PassarTodosActionPerformed(evt);
            }
        });

        Button_PassarUm.setText(">");
        Button_PassarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PassarUmActionPerformed(evt);
            }
        });

        Botao_Corpus_Acima.setBackground(new java.awt.Color(0, 0, 0));
        Botao_Corpus_Acima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MetaAnn/help_icon.png"))); // NOI18N
        Botao_Corpus_Acima.setToolTipText("lang2");
        Botao_Corpus_Acima.setBorder(null);
        Botao_Corpus_Acima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Corpus_AcimaActionPerformed(evt);
            }
        });

        Button_VoltarUm.setText("<");
        Button_VoltarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_VoltarUmActionPerformed(evt);
            }
        });

        Button_VoltarTodos.setText("<<");
        Button_VoltarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_VoltarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Button_PassarUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_PassarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Button_VoltarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_VoltarUm, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelAdvanced)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Botao_Corpus_Acima, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAdvanced, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(Botao_Corpus_Acima, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Button_PassarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_PassarUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_VoltarUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_VoltarTodos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        Botao_Salvar.setText("Salvar");
        Botao_Salvar.setToolTipText("CTRL+S");
        Botao_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SalvarActionPerformed(evt);
            }
        });

        Botao_Cancelar.setText("Cancelar");
        Botao_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Botao_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botao_Cancelar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_Salvar)
                    .addComponent(Botao_Cancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        META_ANN.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void Lista_de_CategoriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lista_de_CategoriasValueChanged

        Lista_de_Dependencias.clearSelection();

    }//GEN-LAST:event_Lista_de_CategoriasValueChanged

    private void Lista_de_DependenciasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lista_de_DependenciasValueChanged

        Lista_de_Categorias.clearSelection();

    }//GEN-LAST:event_Lista_de_DependenciasValueChanged

    private void Botao_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_CancelarActionPerformed
        META_ANN.setEnabled(true);
        this.dispose();
        
        META_ANN.controlarBotoes();
    }//GEN-LAST:event_Botao_CancelarActionPerformed

    private void Acao_Salvar()
    {
        /*
        * Verifica se todos os dados Solicitados foram preenchidos, e caso positivo cria o objeto Categoria
        *   Caso Negativo exibe uma notificação
        */

        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);

        if(TEXTOLIVRE){
            if(Text_Texto_da_Categoria.getText().trim().length()==0){
                JOptionPane.showMessageDialog(null, bundle.getString("erroTextoLivre"), bundle.getString("erroCampoObrig"), JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        else{
            if(OPCOES_MODEL.isEmpty() || OPCOES_MODEL.size()==1){
                JOptionPane.showMessageDialog(null, bundle.getString("erroOpcoes"), bundle.getString("erro"), JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if(!(Text_Nome_Categoria.getText().trim().length()==0) && !(Text_Identificador_da_Categoria.getText().trim().length()==0)){

            Categoria temp = new Categoria();

            temp.setNome_da_Categoria(Text_Nome_Categoria.getText().toUpperCase());
            temp.setIdentificador_da_Categoria(Text_Identificador_da_Categoria.getText().toUpperCase());
            temp.setTipo_da_Categoria(Combo_Tipo_da_Categoria.getSelectedIndex());

            if(TEXTOLIVRE){
                temp.setTexto_da_Categoria(Text_Texto_da_Categoria.getText().toUpperCase());
                OPCOES_MODEL.addElement(temp.getTexto_da_Categoria());
                //temp.AdicionaOpcao(temp.getTexto_da_Categoria());
                temp.setOpcoesModel(OPCOES_MODEL);
            }
            else{
                // CASO SEJA NECESSARIO OBTER AS STRINGS HABILITAR
                // for(Object opcao : OPCOES_MODEL.toArray()){
                    //     temp.AdicionaOpcao((String)opcao);
                    // }
                temp.setOpcoesModel(OPCOES_MODEL);
                temp.setOpcoes(OPCOES);
            }
            
            for(int i=0; i<DEPENDECIAS_DA_CATEGORIA.size(); i++){
                
                String cateDependencia = (String)DEPENDECIAS_DA_CATEGORIA.getElementAt(i);
                
                for( Categoria aux : this.META_ANN.getCategorias()){
                    
                    if( aux.getNome_da_Categoria().equals(cateDependencia)){
                        temp.setDependencias(aux);
                        break;
                    }
                    
                }
            }

            boolean completo;

            if(!EDICAO){
                completo = META_ANN.AdicionaCategoria(temp);
            }
            else{
                completo = META_ANN.EditaCategoria(temp,CATEGORIA_EDITADA);
            }

            if(completo){
                META_ANN.setEnabled(true);
                this.dispose();
            }

        }
        else if(Text_Nome_Categoria.getText().trim().length()==0){
            JOptionPane.showMessageDialog(null, bundle.getString("erroNomeCategoria"), bundle.getString("erroCampoObrig"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        else JOptionPane.showMessageDialog(null, bundle.getString("erroIdentificadorCategoria"), bundle.getString("erroCampoObrig"), JOptionPane.ERROR_MESSAGE);
        
        META_ANN.controlarBotoes();
    }
    
    private void Botao_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SalvarActionPerformed
        this.Acao_Salvar();
    }//GEN-LAST:event_Botao_SalvarActionPerformed

    private void Botao_Opcao_AcimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Opcao_AcimaActionPerformed
        /*
        * Altera a Ordem dos Elementos, deslocando o elemento selecionado para cima
        */
        int indice;
        if(!Lista_de_Opcoes.isSelectionEmpty() && (indice = Lista_de_Opcoes.getSelectedIndex()-1) >= 0){
            String temp = (String)Lista_de_Opcoes.getSelectedValue();
            Opcao tempOpcao = OPCOES.get(indice + 1);
            OPCOES.remove(indice + 1);
            OPCOES.add(indice,tempOpcao);
            OPCOES_MODEL.remove(indice + 1);
            OPCOES_MODEL.add(indice, temp);
            Lista_de_Opcoes.setSelectedIndex(indice);
        }
    }//GEN-LAST:event_Botao_Opcao_AcimaActionPerformed

    private void Botao_Opcao_AbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Opcao_AbaixoActionPerformed
        /*
        * Altera a Ordem dos Elementos, deslocando o elemento selecionado para baixo
        */
        int indice;
        if(!Lista_de_Opcoes.isSelectionEmpty() && (indice = Lista_de_Opcoes.getSelectedIndex()+1) < OPCOES_MODEL.getSize()){
            String temp = (String)Lista_de_Opcoes.getSelectedValue();
            Opcao tempOpcao = OPCOES.get(indice -1);
            OPCOES.remove(indice - 1);
            OPCOES.add(indice,tempOpcao);
            OPCOES_MODEL.remove(indice - 1);
            OPCOES_MODEL.add(indice, temp);
            Lista_de_Opcoes.setSelectedIndex(indice);
        }
    }//GEN-LAST:event_Botao_Opcao_AbaixoActionPerformed

    private void Text_Identificador_da_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Identificador_da_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Identificador_da_CategoriaActionPerformed

    private void Combo_Tipo_da_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Tipo_da_CategoriaActionPerformed
        /*
        * Habilita o TEXT_Texto_da_Categoria e Desabilita a JList caso a Opção "TEXTO LIVRE" seja selecionada no COMBO
        * Desabilita o TEXT_Texto_da_Categoria e Habilita a JList caso a Opção "TEXTO LIVRE" nao seja selecionada no COMBO
        */
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);

        if(Combo_Tipo_da_Categoria.getSelectedIndex()==2){

            Text_Texto_da_Categoria.setText("");
            Text_Texto_da_Categoria.setEnabled(true);
            jLabelTextoCategoria.setText(bundle.getString("textoCategoriaObrig"));
            Lista_de_Opcoes.setEnabled(false);
            Text_Valor_Opcao.setText("");
            Text_Valor_Opcao.setEnabled(false);
            ConfiguraBotoesJlist(false);
            TEXTOLIVRE = true;
            OPCOES_MODEL.clear();
        }
        else{
            Text_Texto_da_Categoria.setText("");
            Text_Texto_da_Categoria.setEnabled(false);
            jLabelTextoCategoria.setText(bundle.getString("textoCategoria"));
            Text_Valor_Opcao.setEnabled(true);
            Lista_de_Opcoes.setEnabled(true);
            ConfiguraBotoesJlist(true);
            TEXTOLIVRE = false;
        }
        
        controlarBotoes();
    }//GEN-LAST:event_Combo_Tipo_da_CategoriaActionPerformed

    private void Lista_de_OpcoesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Lista_de_OpcoesValueChanged

        /*
        * Atualiza o Text_Valor_Opcao com o valor selecionado na List
        */

        if(!Lista_de_Opcoes.isSelectionEmpty()){

            Opcao opcao = OPCOES.get(Lista_de_Opcoes.getSelectedIndex());

            Text_Valor_Opcao.setText(opcao.getValorAnotacao());

        }
        
        controlarBotoes();

    }//GEN-LAST:event_Lista_de_OpcoesValueChanged

    private void Lista_de_OpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_de_OpcoesMouseClicked

        /*
        * Habilita a edição da opção com dois clicks
        */

        if(evt.getClickCount() == 2) Botao_Edita_OpcaoActionPerformed(null);

    }//GEN-LAST:event_Lista_de_OpcoesMouseClicked

    private void Botao_Edita_OpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Edita_OpcaoActionPerformed

        /*
        * !!!! Esse método pode receber um evt NULL !!!!
        *
        * Abre a JFrameOpcao para a Editar a Opção selecionada
        */

        if(!Lista_de_Opcoes.isSelectionEmpty()){
            Opcao opcao = OPCOES.get(Lista_de_Opcoes.getSelectedIndex());
            new JFrameOpcao(this,opcao,locale).setVisible(true);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_Botao_Edita_OpcaoActionPerformed

    private void Botao_Remove_OpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Remove_OpcaoActionPerformed
        /*
        * Remove o elemento selecionado da Lista
        */
        
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);
        
        if(!Lista_de_Opcoes.isSelectionEmpty()){
            
            //Confirmar se o usuário deseja mesmo excluir a categoria
            int resposta = JOptionPane.showConfirmDialog(this, bundle.getString("confirmaRemoverOpcao"), bundle.getString("aviso"), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
            if(resposta == JOptionPane.YES_OPTION)
            {           
                int index = Lista_de_Opcoes.getSelectedIndex();
                OPCOES_MODEL.remove(Lista_de_Opcoes.getSelectedIndex());
                OPCOES.remove(index);
                Text_Valor_Opcao.setText("");
            }
        }
        
        this.controlarBotoes();
    }//GEN-LAST:event_Botao_Remove_OpcaoActionPerformed

    private void Botao_Adiciona_OpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Adiciona_OpcaoActionPerformed

        /*
        * Abre a JFrameOpção para Adicionar uma nova Opção
        */
        new JFrameOpcao(this,locale).setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_Botao_Adiciona_OpcaoActionPerformed

    private void Button_PassarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PassarTodosActionPerformed
        /*
         * Inclui o Nome das Categorias Selecionadas na Lista de Dependencia da presente Categoria
         */
        
        //Remove de CATEGORIAS_EXISTENTES (Lista_de_Categorias) para DEPENDENCIAS_DA_CATEGORIA
        
        while(CATEGORIAS_EXISTENTES.size()!=0){
        
            int index = 0;
            DEPENDECIAS_DA_CATEGORIA.addElement(CATEGORIAS_EXISTENTES.get(index));
            CATEGORIAS_EXISTENTES.remove(index);
            
        }
        
    }//GEN-LAST:event_Button_PassarTodosActionPerformed

    private void Button_PassarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PassarUmActionPerformed
        /*
         * Exclui o Nome das Categorias Selecionadas na Lista de Dependencia da presente Categoria
         */
        
        int[] indices;
        int i, indice;
        List<String> lista = new ArrayList<String>();
        
        if(!Lista_de_Categorias.isSelectionEmpty()){
            
            indices = Lista_de_Categorias.getSelectedIndices();
            Arrays.sort(indices);
            for(i = (indices.length-1); i >= 0; i--)
            {
                indice = indices[i];
                lista.add(CATEGORIAS_EXISTENTES.get(indice).toString());
                CATEGORIAS_EXISTENTES.remove(indice);
            }
            
            for(i = (lista.size() - 1); i >= 0; i--)
                DEPENDECIAS_DA_CATEGORIA.addElement(lista.get(i));
        }
        
    }//GEN-LAST:event_Button_PassarUmActionPerformed

    private void Text_Identificador_da_CategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_Identificador_da_CategoriaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Identificador_da_CategoriaFocusLost

    private void Botao_Corpus_AcimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Corpus_AcimaActionPerformed
        // TODO add your handling code here:
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);
        
        JOptionPane.showMessageDialog(this, bundle.getString("mensagemPanelAvancado1"), bundle.getString("dica"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Botao_Corpus_AcimaActionPerformed

    private void Text_Valor_OpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Valor_OpcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Valor_OpcaoActionPerformed

    private void Button_VoltarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_VoltarUmActionPerformed

        int[] indices;
        int i, indice;
        List<String> lista = new ArrayList<String>();
        
        if(!Lista_de_Dependencias.isSelectionEmpty()){
            
            indices = Lista_de_Dependencias.getSelectedIndices();
            Arrays.sort(indices);
            for(i = (indices.length-1); i >= 0; i--)
            {
                indice = indices[i];
                lista.add(DEPENDECIAS_DA_CATEGORIA.get(indice).toString());
                DEPENDECIAS_DA_CATEGORIA.remove(indice);
            }
            
            for(i = (lista.size() - 1); i >= 0; i--)
                CATEGORIAS_EXISTENTES.addElement(lista.get(i));
        }
        
    }//GEN-LAST:event_Button_VoltarUmActionPerformed

    private void Button_VoltarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_VoltarTodosActionPerformed

        while(DEPENDECIAS_DA_CATEGORIA.size()!=0){
            
            int index = 0;
            CATEGORIAS_EXISTENTES.addElement(DEPENDECIAS_DA_CATEGORIA.get(index));
            DEPENDECIAS_DA_CATEGORIA.remove(index);
            
        }
        
    }//GEN-LAST:event_Button_VoltarTodosActionPerformed
	
    private void carregaListaDeCategorias() {
        
        ArrayList<Categoria> categorias = this.META_ANN.getCategorias();
        
        for(Categoria aux : categorias){
            this.CATEGORIAS_EXISTENTES.addElement(aux.getNome_da_Categoria());
        }
        
    }
    
    private void carregaEstado(Categoria categoria) {
        
        String nomeCategoria = categoria.getNome_da_Categoria(); 
        ArrayList<Integer> remover = new ArrayList();
        
        Text_Nome_Categoria.setText(nomeCategoria);
        Text_Identificador_da_Categoria.setText(categoria.getIdentificador_da_Categoria());
        
       CATEGORIAS_EXISTENTES.remove(CATEGORIAS_EXISTENTES.indexOf(nomeCategoria));
       
       for(Categoria aux : categoria.getDependencias()){
           DEPENDECIAS_DA_CATEGORIA.addElement(CATEGORIAS_EXISTENTES.remove(CATEGORIAS_EXISTENTES.indexOf(aux.getNome_da_Categoria())));
       }
       
       //Verificar dependências e removê-las
       Enumeration enum1 = CATEGORIAS_EXISTENTES.elements();
       while(enum1.hasMoreElements())
       {
           Object item = enum1.nextElement();
           Categoria pai = META_ANN.getCategoria(item.toString());
           
           System.out.println(this.CATEGORIA_EDITADA.getNome_da_Categoria() + " " + pai.getNome_da_Categoria());
           if(META_ANN.verSeTemCiclo(this.CATEGORIA_EDITADA, pai))
               remover.add(CATEGORIAS_EXISTENTES.indexOf(item));
       }
       
       Collections.sort(remover);
       for(int i = remover.size()-1; i >= 0; i--)
           CATEGORIAS_EXISTENTES.remove(i);
        
        int indice = categoria.getTipo_da_Categoria();
        
        Combo_Tipo_da_Categoria.setSelectedIndex(indice);
        
        if(indice != 2){
            
            OPCOES_MODEL = categoria.getCloneOpcoesModel();
            OPCOES       = (ArrayList<Opcao>) categoria.getOpcoes().clone();
            Lista_de_Opcoes.setModel(OPCOES_MODEL);
            ConfiguraBotoesJlist(true);
            TEXTOLIVRE = false;
            
        }
        else{
            
            Text_Texto_da_Categoria.setText( categoria.getTexto_da_Categoria());
            ConfiguraBotoesJlist(false);
            TEXTOLIVRE = true;
            
        }
        
    }
        
    public void internacionaliza(){
        
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);
        
        if(this.EDICAO)
            setTitle("MetaAnn - " + bundle.getString("editarCategoria"));
        else
            setTitle("MetaAnn - " + bundle.getString("adicionarCategoria"));
        jTabbedPane1.setTitleAt(0, bundle.getString("geral"));
        jTabbedPane1.setTitleAt(1, bundle.getString("avancado"));
        jLabelAdvanced.setText(bundle.getString("mensagemPanelAvancado"));
        Botao_Corpus_Acima.setToolTipText(bundle.getString("mensagemPanelAvancado1"));
        jLabelIdentificadorCategoria.setText(bundle.getString("identificadorCategoria"));
        jLabelNomeCategoria.setText(bundle.getString("nomeCategoria"));
        jLabel_Valor_Categoria.setText(bundle.getString("valorOpcao"));
        jLabelOpcoes.setText(bundle.getString("opcoes"));
        jLabelTextoCategoria.setText(bundle.getString("textoCategoria"));
        jLabelTipoCategoria.setText(bundle.getString("tipoCategoria"));
        Botao_Adiciona_Opcao.setText(bundle.getString("adicionar"));
        Botao_Cancelar.setText(bundle.getString("cancelar"));
        Botao_Edita_Opcao.setText(bundle.getString("editar"));
        Botao_Remove_Opcao.setText(bundle.getString("remover"));
        Botao_Salvar.setText(bundle.getString("salvar"));
        Combo_Tipo_da_Categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { bundle.getString("opcoesMutualmenteExcludentes"), bundle.getString("listaSimples"), bundle.getString("textoLivre") }));
    }
    
    public void ConfiguraBotoesJlist(boolean estado){
       
        /*
         *  Habilita ou Desabita os Botões para manipulação da Jlist
         */
        
        Botao_Adiciona_Opcao.setEnabled(estado);
        Botao_Edita_Opcao.setEnabled(estado);
        Botao_Remove_Opcao.setEnabled(estado);
        Botao_Opcao_Acima.setEnabled(estado);
        Botao_Opcao_Abaixo.setEnabled(estado);
    }
    
    public boolean AdicionaOpcao(Opcao nova_opcao){
        /*
         * Adiciona Elemento na Jlist
         */
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);
        boolean identico = false;
        
        for(Opcao aux : OPCOES){
            if(aux.getValorUsuario().equals(nova_opcao.getValorUsuario())){
                identico = true;
                JOptionPane.showMessageDialog(null, bundle.getString("erroAdicionaNomeOpcao"), bundle.getString("erro"), JOptionPane.ERROR_MESSAGE);
                break;
            }
            
            if(aux.getValorAnotacao().equals(nova_opcao.getValorAnotacao())){
                identico = true;
                JOptionPane.showMessageDialog(null, bundle.getString("erroAdicionaValorOpcao"), bundle.getString("erro"), JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(!identico){
            OPCOES.add(nova_opcao);
            OPCOES_MODEL.addElement(nova_opcao.getValorUsuario());
        }
        
        return !identico;
        
    }
    
    public boolean EditaOpcao(Opcao temp, Opcao opcao_editada){
         /*
         * Edita Elemento na Jlist
         */
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameCategoria.JFrameCategoria", locale);
        boolean identico = false;
        
        for(Opcao aux : OPCOES){
            
            if(aux.getValorUsuario().equals(temp.getValorUsuario()) && aux != opcao_editada){
                identico = true;
                JOptionPane.showMessageDialog(null, bundle.getString("erroEditaNomeOpcao"), "MetaAnn", JOptionPane.ERROR_MESSAGE);
                break;
            }
            
            if(aux.getValorAnotacao().equals(temp.getValorAnotacao()) && aux != opcao_editada){
                identico = true;
                JOptionPane.showMessageDialog(null, bundle.getString("erroEditaValorOpcao"), "MetaAnn", JOptionPane.ERROR_MESSAGE);
                break;
            }
        }
        
        if(!identico){
            int indice = Lista_de_Opcoes.getSelectedIndex();
            OPCOES.remove(indice);
            OPCOES.add(indice,temp);
            Lista_de_Opcoes.setSelectedIndex(indice);
            OPCOES_MODEL.setElementAt(temp.getValorUsuario(), indice);
            Lista_de_OpcoesValueChanged(null);
        }
        
        return !identico;
        
    }
    
    protected void controlarBotoes()
    {
        if(this.Lista_de_Opcoes.getSelectedIndex()<0)
        {
            this.Botao_Edita_Opcao.setEnabled(false);
            this.Botao_Remove_Opcao.setEnabled(false);
        }
        else
        {
            this.Botao_Edita_Opcao.setEnabled(true);
            this.Botao_Remove_Opcao.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Adiciona_Opcao;
    private javax.swing.JButton Botao_Cancelar;
    private javax.swing.JButton Botao_Corpus_Acima;
    private javax.swing.JButton Botao_Edita_Opcao;
    private javax.swing.JButton Botao_Opcao_Abaixo;
    private javax.swing.JButton Botao_Opcao_Acima;
    private javax.swing.JButton Botao_Remove_Opcao;
    private javax.swing.JButton Botao_Salvar;
    private javax.swing.JButton Button_PassarTodos;
    private javax.swing.JButton Button_PassarUm;
    private javax.swing.JButton Button_VoltarTodos;
    private javax.swing.JButton Button_VoltarUm;
    private javax.swing.JComboBox Combo_Tipo_da_Categoria;
    private javax.swing.JList Lista_de_Categorias;
    private javax.swing.JList Lista_de_Dependencias;
    private javax.swing.JList Lista_de_Opcoes;
    private javax.swing.JTextField Text_Identificador_da_Categoria;
    private javax.swing.JTextField Text_Nome_Categoria;
    private javax.swing.JTextField Text_Texto_da_Categoria;
    private javax.swing.JTextField Text_Valor_Opcao;
    private javax.swing.JLabel jLabelAdvanced;
    private javax.swing.JLabel jLabelIdentificadorCategoria;
    private javax.swing.JLabel jLabelNomeCategoria;
    private javax.swing.JLabel jLabelOpcoes;
    private javax.swing.JLabel jLabelTextoCategoria;
    private javax.swing.JLabel jLabelTipoCategoria;
    private javax.swing.JLabel jLabel_Valor_Categoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        Botao_Corpus_Acima.setBackground(new java.awt.Color(0, 0, 0, 0));
    }
}
