/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MetaAnn;

import java.awt.Desktop;
import java.net.URI;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ctcca
 */
public class JFrameSobre extends javax.swing.JDialog {

    /**
     * Creates new form ModalSobre
     */
    public JFrameSobre(Locale locale) {
        initComponents();
        this.locale = locale;
        
        StyledDocument doc = TextPaneSobre.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_JUSTIFIED);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        
        //Coisas feitas por fora
        setModal(true);
        setLocationRelativeTo(null);
        internacionaliza();
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelVersao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPaneSobre = new javax.swing.JTextPane();
        LabelMaisInfo = new javax.swing.JLabel();
        LabelLink = new javax.swing.JLabel();
        LabelLogotipo2 = new javax.swing.JLabel();
        LabelCredito = new javax.swing.JLabel();
        LabelLink2 = new javax.swing.JLabel();

        setTitle("Sobre o MetaAnn");
        setResizable(false);

        LabelVersao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelVersao.setText("Versão 1.0");

        TextPaneSobre.setEditable(false);
        TextPaneSobre.setBackground(new java.awt.Color(240, 240, 240));
        TextPaneSobre.setText("O MetaAnn é um gerador de anotadores, isto é, uma ferramenta utilizada para a configuração e criação de ferramentas de anotação. Dentro do MetaAnn, esquemas de anotação são deﬁnidos como uma série de categorias a serem aplicadas a cada unidade básica de anotação do corpus de estudo. Nele, o usuário é capaz de determinar o corpus a ser anotado, configurar as categorias e as opções e definir dependência entre as mesmas. Ao finalizar, o sistema gera a ferramenta de anotação conforme configurado pelo usuário e também disponibiliza o código-fonte, caso o pesquisador queira fazer alguma alteração.");
        TextPaneSobre.setAutoscrolls(false);
        jScrollPane2.setViewportView(TextPaneSobre);

        LabelMaisInfo.setText("Mais informações em:");

        LabelLink.setText("<html><a href=\"#\">http://www.each.usp.br/norton/resdial/</a></html>");
        LabelLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLinkMouseClicked(evt);
            }
        });

        LabelLogotipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MetaAnn/icone_texto.png"))); // NOI18N

        LabelCredito.setText("Imagem do logotipo desenvolvida por");

        LabelLink2.setText("<html><a href=\"#\">OCHA</a></html>");
        LabelLink2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelLink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLink2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelLogotipo2)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelVersao)
                                .addGap(187, 187, 187))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(LabelMaisInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(LabelCredito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLink2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelLogotipo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMaisInfo)
                    .addComponent(LabelLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCredito)
                    .addComponent(LabelLink2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLinkMouseClicked
        // TODO add your handling code here:
        try
        {
            Desktop.getDesktop().browse(new URI("http://www.each.usp.br/norton/resdial/"));
        }
        catch(Exception e)
        {
            //Se o link não for aberto esta excecao nao sera tratada
        }
    }//GEN-LAST:event_LabelLinkMouseClicked

    private void LabelLink2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLink2MouseClicked
        try
        {
            Desktop.getDesktop().browse(new URI("https://www.flaticon.com/authors/ocha"));
        }
        catch(Exception e)
        {
            //Se o link não for aberto esta excecao nao sera tratada
        }
    }//GEN-LAST:event_LabelLink2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCredito;
    private javax.swing.JLabel LabelLink;
    private javax.swing.JLabel LabelLink2;
    private javax.swing.JLabel LabelLogotipo2;
    private javax.swing.JLabel LabelMaisInfo;
    private javax.swing.JLabel LabelVersao;
    private javax.swing.JTextPane TextPaneSobre;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private Locale locale;
    
private void translateDescr(boolean portugues)
{
    if(!portugues)
    {
        setTitle("About T-Seg");
        TextPaneSobre.setText("T-Seg is a tool for labeling and segmentation of texts used for defining minimum units of annotation corpora. In it, you define how you want to be automatically segmenting (by rules), and may also manually mark the segments in one source text. If the marking is done manually, multiple users can perform the same task, then fitting the system to determine the confidence level marking scheme used, based on an analysis the degree of agreement between human markers.");
        LabelVersao.setText("Version: 1.01");
        LabelMaisInfo.setText("For more information:");
    }
}

    private void internacionaliza()
    {
        ResourceBundle bundle = ResourceBundle.getBundle("MetaAnn.Idioma.JFrameSobre.JFrameSobre", this.locale);
        setTitle(bundle.getString("titulo"));
        TextPaneSobre.setText(bundle.getString("textoSobre"));
        LabelVersao.setText(bundle.getString("versao"));
        LabelMaisInfo.setText(bundle.getString("maisInfos"));
        LabelCredito.setText(bundle.getString("logoImg"));
    }
}
