/*
    Este arquivo é parte do programa AgreeCalc
    
    AgreeCalc é um software livre; você pode redistribui-lo e/ou 

    modifica-lo dentro dos termos da Licença Pública Geral GNU como 

    publicada pela Fundação do Software Livre (FSF); na versão 2 da 

    Licença, ou qualquer versão.



    Este programa é distribuido na esperança que possa ser  util, 

    mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer

    MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a

    Licença Pública Geral GNU para maiores detalhes.



    Você deve ter recebido uma cópia da Licença Pública Geral GNU

    junto com este programa, se não, escreva para a Fundação do Software

    Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 
 */


package graphicInterface;

import ferramentaic.RUser;
import java.io.File;
import java.io.FileFilter;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import workers.AgreeCalcWorker;
import workers.CorpusReader;

/**
 *
 * @author Alexandre
 */
public class SelectionWindowGUI extends javax.swing.JFrame {

    /**
     * Creates new form SelectionWindowGUI
     */
    public Locale local = new Locale("en");
    public boolean first = true;
    ResourceBundle bundle;
    
    //adicionado para a versão 1.2
    private String parent; //para decidir para onde voltar (quando for possível)
    private boolean corpusReset; //se o usuário pediu para trocar o corpus e já clicou em avançar uma vez
                                 //o corpus em RUser foi apagado, não dá pra voltar para a FerramentaGUI
    
    public SelectionWindowGUI(String language, String parentClassName) {
        this.parent=parentClassName;
        corpusReset=false;
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("myicon.png")).getImage());  
        internacionaliza(language);
    }

    void internacionaliza(String loca1){
        if(loca1.equals("en")) local = new Locale(loca1, "US");
        else local = new Locale(loca1, "BR");
        
        bundle = ResourceBundle.getBundle("i18n.MyBundle", local);
        jLabel1.setText(bundle.getString("SelectCorpus"));
        jLabel2.setText(bundle.getString("SelectCorpusExplain"));
        Botao_avancar.setText(bundle.getString("Advance"));
        Botao_apagar.setText(bundle.getString("ClearSelectWindow"));
        Botao_voltar.setText(bundle.getString("Back"));
        this.setTitle(bundle.getString("SecondScreen"));
        //System.out.println(EngFirst);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Texto_caminho = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Botao_procurar = new javax.swing.JButton();
        Botao_avancar = new javax.swing.JButton();
        Botao_apagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Botao_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Texto_caminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_caminhoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Selecione a pasta do CORPUS de anotações:");

        Botao_procurar.setText("...");
        Botao_procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_procurarActionPerformed(evt);
            }
        });

        Botao_avancar.setText("Avançar");
        Botao_avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_avancarActionPerformed(evt);
            }
        });

        Botao_apagar.setText("Limpar");
        Botao_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_apagarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        jLabel2.setText("(As anotações aqui contidas deverão pertencer ao mesmo esquema de anotação)");
        jLabel2.setToolTipText("");

        Botao_voltar.setText("Voltar");
        Botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Botao_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Texto_caminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Texto_caminho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Botao_procurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_procurarActionPerformed
        // TODO add your handling code here:
         JFileChooser open = new JFileChooser();
         
         open.setFileSelectionMode(1);
         open.setApproveButtonText(bundle.getString("Select"));
         open.setDialogTitle(bundle.getString("CorpusPath"));
            int op = open.showOpenDialog(this);  
            if(op == JFileChooser.APPROVE_OPTION){  
               File arq = open.getSelectedFile();  
               String path = arq.toString();  
                      //aqui você testa se a string recebeu o caminho do arquivo  
                      Texto_caminho.setText(path);
                      //Texto_caminho.setEditable(false);
                     
		//System.out.println("CATE, INTE e CONS");
		
            }  
         
//        ArchiveGUI arq = new ArchiveGUI();
//        arq.setVisible(true);
    }//GEN-LAST:event_Botao_procurarActionPerformed

    private void Botao_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_apagarActionPerformed
        // TODO add your handling code here:
        Texto_caminho.setEditable(true);
        Texto_caminho.setText("");
    }//GEN-LAST:event_Botao_apagarActionPerformed

    private void Botao_avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_avancarActionPerformed
        // TODO add your handling code here:
        File novo;
        if(Texto_caminho.getText()!=null){
            if(new File(Texto_caminho.getText()).exists()){
                RUser r = RUser.getInstance();
                r.internacionaliza(local.getLanguage());
                
                boolean continuar = true;
                if(parent.equals(FerramentaGUI.class.getCanonicalName())){
                    continuar = !MainGUI.showForgetCorpusMsg; //se nao for pra mostrar a tela, sempre continua
                    JCheckBox check = new JCheckBox(bundle.getString("DontShowAgain"));
                    if(MainGUI.showForgetCorpusMsg){
                        int diagResp = JOptionPane.showOptionDialog(null,
                                        bundle.getString("QuestionForgetCorpus"),
                                        bundle.getString("Attention"),
                                        JOptionPane.YES_NO_OPTION,
                                        JOptionPane.WARNING_MESSAGE,
                                        null,
                                        new Object[]{check,bundle.getString("Yes"),bundle.getString("No")},
                                        bundle.getString("No"));
                        if(check.isSelected()){
                            MainGUI.showForgetCorpusMsg=false;
                            MainGUI.gravarConfigs();
                        }
                        if(diagResp == 1) //posição do Yes
                            continuar=true;
                        else continuar=false;
                    }
                }
                
                if(continuar){
                    corpusReset=true;
                    if(parent.equals(FerramentaGUI.class.getCanonicalName())) 
                        Botao_voltar.setEnabled(false);
                    r.reset();

                    AgreeCalcWorker worker = new CorpusReader(bundle, Texto_caminho.getText());
                    DialogoProgresso diag = new DialogoProgresso(this.getRootPane(),worker,bundle);
                    diag.setVisible(true);

                    if(diag.getResponse().getClass().equals(Boolean.class)){
                        boolean resp =(boolean) diag.getResponse();
                        if(resp){
                            this.dispose();
                            FerramentaGUI next = FerramentaGUI.getInstance();
                            next.internacionaliza(local.getLanguage());
                            next.exibirInfos();
                            //next.setSelectedTab(0);
                            next.setVisible(true);
                        }
                    }
                }
                    
            }else{
                //nao existe o arquivo selecionado..
            }
        }
    }//GEN-LAST:event_Botao_avancarActionPerformed

    private void Texto_caminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_caminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto_caminhoActionPerformed

    private void Botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_voltarActionPerformed
        if(parent.equals(MainGUI.class.getCanonicalName())){ //se a janela pai foi a tela de apresentação
            this.dispose();
            MainGUI voltar = MainGUI.getInstance();
            voltar.setVisible(true);
        } else if(!corpusReset && parent.equals(FerramentaGUI.class.getCanonicalName())){ //se a janela pai foi a tela principal
            this.dispose();
            FerramentaGUI voltar = FerramentaGUI.getInstance();
            voltar.setVisible(true);
        }
    }//GEN-LAST:event_Botao_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String lingua = "en";
    private static String callerClassName;
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        lingua = args[0];
        callerClassName=args[1];
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SelectionWindowGUI(lingua, callerClassName).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_apagar;
    private javax.swing.JButton Botao_avancar;
    private javax.swing.JButton Botao_procurar;
    private javax.swing.JButton Botao_voltar;
    private javax.swing.JTextField Texto_caminho;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
